---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: public/uploads
public_path: "/public/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node/node:16.13.2
  mount_path: "/home/node/app"
  working_dir: "/home/node/app"
  instant_preview_command: npm run dev
